### PR TITLE
Enforce user literals parsing

### LINKED ISSUE #11: 🐛 User defined literals should fail compilation for invalid values

### PR DESCRIPTION
**Pull request by rykovv**
Closes #11 

Current implementation contains a 🐛 bug. Compilation will fail for invalid values captured by user literals. Such weakness puts in danger the whole purpose of the safety library. Stronger user literals parsing is needed.

This PR adds strong support for positive decimal and hexadecimal numbers. The support is provided through creation of three concepts: `hex_integer` and `decimal_integer`. These concepts match provided values with intended types and dispatch appropriate parsing function. So, additional safety is provided.

### CODE REVIEW

**Comment by elbeno** [comment]
UDLs will never receive the negative sign? Unary minus is an operator, not part of a literal. https://godbolt.org/z/M1hneGfj7

**Comment by rykovv** [comment]
See the point. My understanding wasn't correct. Hence, think it can be split in following steps:

1. Create additional minus struct but derived from unary_op in dsl/minus.hpp
2. Specialize for Primitive. Will need to swap min with max in ival and make both negative. 
3. Does specialization for mask make sense?
4. Add unary minus operator overload

Am I missing something?

**Comment by lukevalenty** [comment]
> See the point. My understanding wasn't correct. Hence, think it can be split in following steps:
> 
> 1. Remove netagive decimal integer concept
> 2. Create additional minus struct but derived from unary_op in dsl/minus.hpp
> 3. Specialize for Primitive. Will need to swap min with max in ival and make both negative.
> 4. Does specialization for mask make sense?
> 5. Add unary minus operator overload
> 
> Am I missing something?

I think you can just remove the negative decimal integer concept and it's fine. The library should already handle unary minus.

File: include/safe/detail/concepts.hpp [hunk 1]
```diff
@@ -15,4 +15,35 @@ concept range_like = requires(R r) {
...
+                                     Char - 'a' >= 0 && Char - 'f' <= 5);
+};
+
+template <char Char> constexpr bool is_hex_digit_v = is_hex_digit<Char>::value;
+
+template <typename T, char Char0, char Char1, char... Chars>
+concept positive_hex_integer = requires {
+    requires std::unsigned_integral<T>;
+} && (is_0_v<Char0> && is_x_v<Char1> && (is_hex_digit_v<Chars> && ...));
+} // namespace safe::detail
```
Comment (elbeno) [inline include/safe/detail/concepts.hpp:49]: **suggestion**: You have a mix of `constexpr bool`s, `bool_constant` types, and concepts here. I would make them all concepts and express the subsumption relationships clearly.

File: include/safe/detail/concepts.hpp [hunk 2]
```diff
@@ -15,4 +15,35 @@ concept range_like = requires(R r) {
...
 };
-} // namespace safe::detail
\ No newline at end of file
+
+template <char Char>
+constexpr bool is_decimal_digit_v = Char - '0' >= 0 && Char - '0' <= 9;
+
+template <typename T, char... Chars>
+concept positive_decimal_integer = requires { requires std::integral<T>; } &&
+                                   (is_decimal_digit_v<Chars> && ...);
```
Comment (elbeno) [inline include/safe/detail/concepts.hpp:24]: **issue**: Rather than using a nested concept, just put the concept itself. So:
```cpp
template <typename T, char... Chars>
concept positive_decimal_integer = std::integral<T> &&
                                   (is_decimal_digit_v<Chars> && ...);
```
That will enable the compiler to see subsumption, which means easier overload sets.

File: include/safe/detail/concepts.hpp [hunk 3]
```diff
@@ -15,4 +15,35 @@ concept range_like = requires(R r) {
     { r.begin() } -> iter_like;
     r.end();
 };
-} // namespace safe::detail
\ No newline at end of file
+
+template <char Char>
+constexpr bool is_decimal_digit_v = Char - '0' >= 0 && Char - '0' <= 9;
```
Comment (elbeno) [inline include/safe/detail/concepts.hpp:20]: **suggestion**: Why not `Char >= '0' and Char <= '9'` ? Is the subtraction/integral promotion giving us anything?

**Comment by rykovv** [comment]
> I think you can just remove the negative decimal integer concept and it's fine. The library should already handle unary minus.

Gotcha. Haven't seen anything in [dsl/minus.hpp](https://github.com/intel/safe-arithmetic/blob/main/include/safe/dsl/minus.hpp), but found later in [var](https://github.com/intel/safe-arithmetic/blob/71ceed24c83b48d0184a1476e62631620a8521df/include/safe/var.hpp#L135-L138).

**Comment by rykovv** [comment]
Restructuring the PR.

File: include/safe/detail/concepts.hpp (hunk 3 above)
Comment (rykovv) [reply include/safe/detail/concepts.hpp:20]: Agree. No benefit from subtraction. Like to how the suggestion reads

File: include/safe/detail/concepts.hpp (hunk 1 above)
Comment (rykovv) [reply include/safe/detail/concepts.hpp:49]: Start getting the idea of how to better express concepts. `requires` would normally be used when we want to handle a  value of certain type, like [here](https://github.com/intel/safe-arithmetic/blob/main/include/safe/detail/concepts.hpp#L7)

**Comment by rykovv** [comment]
Apologize for messing everything up. Trying to find a good git manager. Will reopen tomorrow.

**Comment by rykovv** [comment]
@elbeno are there any specific requirements for clang-format? Is it based on LLVM or Google?

**Comment by rykovv** [comment]
@elbeno which parameters should I use to properly apply `clang-format`? Couldn't find clues in `git-clang-format.py`

**Comment by elbeno** [comment]
> @elbeno which parameters should I use to properly apply `clang-format`? Couldn't find clues in `git-clang-format.py`

Build the target(s) `fix-clang-format` and `check-clang-format`. Note that cmake finds `clang-format`/`clang-tidy` alongside the compiler its using. The CI on this repo currently uses clang-17 for the formatting. (Which is old; this repo needs to be updated to take advantage of clang-18. But one thing at a time.)

**Comment by rykovv** [comment]
@elbeno I'm getting the code formatted with `clang-format` / `clang-tidy`, alas with wrong formatting rules (default). I don't see `.clang-format` file anywhere in the repo, but rather included in `.gitignore`. If the `.clang-format` file is not part of the repo, how a common style is enforced?

**Comment by rykovv** [comment]
I've noticed unary negation is not supported by unsigned types. Would be a topic for another PR.

**Comment by elbeno** [comment]
This repo pulls in various CI stuff -- including `.clang-format` -- from https://github.com/intel/cicd-repo-infrastructure. Running cmake should produce a `.clang-format` file (symlinked).

**Comment by elbeno** [comment]
With a clean repo, what I normally do is:

```bash
$ cmake -Bbuild
$ TOOLCHAIN_ROOT=/usr/lib/llvm-17 cmake --preset clang --fresh
$ ninja -C build <target>
```

The first cmake run sets up the symlinks (including the presets file. This is only necessary once. The second cmake run is the "real" one that uses llvm-17 (installed from the script at apt.llvm.org) and the preset from the CICD repo. After that, you can build any target you like.

**Comment by rykovv** [comment]
This method doesn't work in Windows. Looks like presets expect clang++ binaries to be in Linux-based directories (`/usr/bin`). You've mentioned something about WSL (Windows Subsystem for Linux). Is there a way to get everything setup there? Otherwise, I'll need to install a Linux distro for C++ dev.

**Comment by elbeno** [comment]
WSL will work.

**Comment by rykovv** [comment]
Will try to get it working with WSL

**Comment by rykovv** [comment]
So, still struggling to get it working:

Ran

```bash
$ sudo apt install libc-bin
$ sudo apt install build-essential
$ llvm.sh 17 # script from apt.llvm.org
$ sudo apt install clang-tools-17 clang-format-17 clang-tidy-17

$ cd safe-arithmetic
$ cmake -Bbuild
$ TOOLCHAIN_ROOT=/usr/lib/llvm-17 cmake --preset clang --fresh
$ ninja -C build check-clang-format # failed
```

The last command faild with error: Format.cmake: cannot run because clang-format and/or python not found
So, I setup up the symbolic links

```bash
$ ln -s /usr/bin/clang-format-17 /usr/bin/clang-format
$ ln -s /usr/bin/clang-tidy-17 /usr/bin/clang-tidy
$ ln -s /usr/bin/python3 /usr/bin/python
```

That didn't help. So, `ninja -C build check-clang-format` is still not working.

On the other hand, I've tried `ninja -C build all`
It also failed

```
/safe-arithmetic/test/safe/big_integer/detail/minus.cpp
In file included from /root/safe-arithmetic/test/safe/big_integer/detail/minus.cpp:1:
In file included from /root/safe-arithmetic/test/safe/big_integer/detail/properties.hpp:3:
/root/safe-arithmetic/include/safe/big_integer/detail/storage.hpp:6:10: fatal error: 'compare' file not found
    6 | #include <compare>
      |          ^~~~~~~~~
1 error generated.
```

File: include/safe/int.hpp [hunk 4]
```diff
@@ -58,16 +58,43 @@ template <auto min, auto max> using ival_u64 = var<uint64_t, ival<min, max>>;
...
+    requires hex_integer<T, Char0, Char1, Chars...>
+[[nodiscard]] static constexpr auto to_constant() {
+    constexpr T value = []() {
+        constexpr std::array<char, sizeof...(Chars)> chars{Chars...};
+        T sum = 0;
+
+        for (char c : chars) {
+            if (not is_delimiter(c)) {
+                T const digit =
+                    c > '9' ? c >= 'a' ? c - 'a' + 10 : c - 'A' + 10 : c - '0';
```
Comment (elbeno) [inline include/safe/int.hpp:95]: **suggestion**: Instead of nested ternary operator, how do you feel about e.g.
`T const digit = c <= '9' ? c - '0' : (c & 0b1101'1111) - 'A' + 10;`

**Review by elbeno — APPROVED** [review]

File: include/safe/int.hpp (hunk 4 above)
Comment (rykovv) [reply include/safe/int.hpp:95]: I see, the difference between upper and lower case in ascii table is the presence of the 6th bit. Didn't know about it. I like it this nerdy approach! Will leave an explanatory comment if somebody like me will stuble

**Review by elbeno — APPROVED** [review]
